/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package policedbms;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author FreezinFire
 */
public class CriminalDisplay extends javax.swing.JFrame {

    /**
     * Creates new form CriminalDisplay
     */
    public CriminalDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crimNoTF = new javax.swing.JTextField();
        no_of_crimesTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aliasTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        categoryTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        date_of_birthTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        times_arrestedTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        times_punishedTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        statusTF = new javax.swing.JTextField();
        locationL = new javax.swing.JLabel();
        imageL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(576, 554));
        setMinimumSize(new java.awt.Dimension(576, 554));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Criminal No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 43, -1, -1));

        crimNoTF.setEditable(false);
        getContentPane().add(crimNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 40, 167, -1));

        no_of_crimesTF.setEditable(false);
        getContentPane().add(no_of_crimesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 124, 167, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 71, -1, -1));

        jLabel3.setText("Alias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 99, -1, -1));

        aliasTF.setEditable(false);
        getContentPane().add(aliasTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 96, 167, -1));

        jLabel4.setText("No. Of Crimes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 127, -1, -1));

        nameTF.setEditable(false);
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 68, 167, -1));

        jLabel5.setText("Category");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 155, -1, -1));

        categoryTF.setEditable(false);
        getContentPane().add(categoryTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 152, 167, -1));

        jLabel6.setText("D.O.B.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 183, -1, -1));

        date_of_birthTF.setEditable(false);
        getContentPane().add(date_of_birthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 180, 167, -1));

        jLabel7.setText("City");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 211, -1, -1));

        cityTF.setEditable(false);
        getContentPane().add(cityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 208, 167, -1));

        times_arrestedTF.setEditable(false);
        getContentPane().add(times_arrestedTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 242, 167, -1));

        jLabel8.setText("Arrest Count");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 245, -1, -1));

        times_punishedTF.setEditable(false);
        getContentPane().add(times_punishedTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 270, 167, -1));

        jLabel9.setText("Punishment Count");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 273, -1, -1));

        jLabel10.setText("Status");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 301, -1, -1));

        statusTF.setEditable(false);
        getContentPane().add(statusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 298, 167, -1));

        locationL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        locationL.setFocusable(false);
        locationL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(locationL, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 242, 244, 236));

        imageL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageL.setFocusable(false);
        imageL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(imageL, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 40, 189, 190));

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        getContentPane().add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 438, -1, 40));

        updateBTN.setText("Update Info.");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });
        getContentPane().add(updateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 438, -1, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here
        this.dispose();
        
    }//GEN-LAST:event_backBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
        String Criminal_no = crimNoTF.getText();
        String name = nameTF.getText();
        String alias = aliasTF.getText();
        String crimes = no_of_crimesTF.getText();
        String catagory = categoryTF.getText();
        String date = date_of_birthTF.getText();
        String city = cityTF.getText();
        String aressted = times_arrestedTF.getText();
        String punished = times_punishedTF.getText();
        String status = statusTF.getText();
try {
    Class.forName("java.sql.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/area51", "root", "rootroot");
    Statement stmt = con.createStatement();
    String query = "Update chor " +
            "set criminal_no = '"+Criminal_no+"'," +
            "name = '"+name+"'," +
            "alias = '"+alias+"'," +
            "no_of_crimes = "+crimes+"," +
            "catagory = '"+catagory+"'," +
            "date_of_birth = "+date+"," +
            "city = '"+city+"'," +
            "times_punished = "+aressted+"," +
            "times_punished = "+punished+"," +
            "status = '"+status+"' " +
            "where criminal_no = '"+Criminal_no+"';";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this, "Database Updated!");
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_updateBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriminalDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriminalDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriminalDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriminalDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriminalDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField aliasTF;
    private javax.swing.JButton backBTN;
    public javax.swing.JTextField categoryTF;
    public javax.swing.JTextField cityTF;
    public javax.swing.JTextField crimNoTF;
    public javax.swing.JTextField date_of_birthTF;
    public javax.swing.JLabel imageL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel locationL;
    public javax.swing.JTextField nameTF;
    public javax.swing.JTextField no_of_crimesTF;
    public javax.swing.JTextField statusTF;
    public javax.swing.JTextField times_arrestedTF;
    public javax.swing.JTextField times_punishedTF;
    public javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
