/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package policedbms;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FreezinFire
 */
public class PoliceMain extends javax.swing.JFrame {

    /**
     * Creates new form CriminalMain
     */
    public PoliceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        showAllBTN = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        newEntryBTN = new javax.swing.JButton();
        infoBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        critCB = new javax.swing.JComboBox<>();
        searchTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        showAllBTN.setText("Show All");
        showAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllBTNActionPerformed(evt);
            }
        });

        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        newEntryBTN.setText("New Entry");
        newEntryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryBTNActionPerformed(evt);
            }
        });

        infoBTN.setText("Complete Info.");
        infoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBTNActionPerformed(evt);
            }
        });

        searchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.jpg"))); // NOI18N
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        critCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "fname", "sname", "post", "city_assigned", "dob", "gender", "address", "phone", "mail", "marital_stat", "password" }));

        dataTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID No.", "Name", "Designation", "Posting"
            }
        ));
        jScrollPane1.setViewportView(dataTB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newEntryBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showAllBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(critCB, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchTF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(clearBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(critCB)
                    .addComponent(searchTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEntryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) dataTB.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_clearBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        String crit = (String) critCB.getSelectedItem();
        String search = searchTF.getText();
        DefaultTableModel model = (DefaultTableModel) dataTB.getModel();
        try{
    Class.forName("java.sql.Driver");

    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/area51", "root", "rootroot");
    Statement stmt = con.createStatement();
    String query = "Select id, sname, post, city_assigned from cops where "+crit+" = '"+search+"';";
    ResultSet rs = stmt.executeQuery(query);

    while(rs.next()){
        model.addRow(new Object[]{rs.getString("id"),rs.getString("sname"),rs.getString("post"),rs.getString("city_assigned")});
    }
    rs.close();
    stmt.close();
    con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_searchBTNActionPerformed

    private void showAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBTNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) dataTB.getModel();
        try{
            Class.forName("java.sql.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/area51", "root", "rootroot");
            Statement stmt = con.createStatement();
            String query = "Select id, sname, post, city_assigned from cops;";
            ResultSet rs = stmt.executeQuery(query);

            while(rs.next()){
                model.addRow(new Object[]{rs.getString("id"),rs.getString("sname"),rs.getString("post"),rs.getString("city_assigned")});
            }
            rs.close();
            stmt.close();
            con.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_showAllBTNActionPerformed

    private void newEntryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryBTNActionPerformed
        // TODO add your handling code here:
        NewPol n = new NewPol();
        n.setVisible(true);
    }//GEN-LAST:event_newEntryBTNActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
        int row = dataTB.getSelectedRow();
        String id = dataTB.getModel().getValueAt(row, 0).toString();
        PoliceDisplay c = new PoliceDisplay();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/area51", "root", "rootroot");
            Statement stmt = con.createStatement();
            String query = "Select * from cops where id = "+id+";";
            ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
        c.setVisible(true);
        c.updateBTN.setVisible(true);
        c.idTF.setText(""+rs.getInt("id"));
        c.fnameTF.setText(rs.getString("fname"));
        c.snameTF.setText(rs.getString("sname"));
        c.postTF.setText(rs.getString("post"));
        c.cityAssignedTF.setText(rs.getString("city_assigned"));
        c.dobTF.setText(rs.getString("dob"));
        c.genderTF.setText(rs.getString("gender"));
        c.addressTF.setText(rs.getString("address"));
        c.phoneTF.setText(""+rs.getLong("phone"));
        c.emailTF.setText(rs.getString("mail"));
        c.maritalTF.setText(rs.getString("marital_stat"));
        c.imageL.setIcon(new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\PoliceDBMS\\src\\resources\\Police\\"+rs.getString("id")+".jpg"));

        c.idTF.setEditable(true);
        c.fnameTF.setEditable(true);
        c.snameTF.setEditable(true);
        c.postTF.setEditable(true);
        c.cityAssignedTF.setEditable(true);
        c.dobTF.setEditable(true);
        c.addressTF.setEditable(true);
        c.genderTF.setEditable(true);
        c.phoneTF.setEditable(true);
        c.emailTF.setEditable(true);
        c.maritalTF.setEditable(true);
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_updateBTNActionPerformed

    private void infoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBTNActionPerformed
        // TODO add your handling code here:
        int row = dataTB.getSelectedRow();
        String id = dataTB.getModel().getValueAt(row, 0).toString();
        PoliceDisplay c = new PoliceDisplay();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/area51", "root", "rootroot");
            Statement stmt = con.createStatement();
            String query = "Select * from cops where id = "+id+";";
            ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
        c.setVisible(true);
        c.updateBTN.setVisible(false);
        c.idTF.setText(""+rs.getInt("id"));
        c.fnameTF.setText(rs.getString("fname"));
        c.snameTF.setText(rs.getString("sname"));
        c.postTF.setText(rs.getString("post"));
        c.cityAssignedTF.setText(rs.getString("city_assigned"));
        c.dobTF.setText(rs.getString("dob"));
        c.genderTF.setText(rs.getString("gender"));
        c.addressTF.setText(rs.getString("address"));
        c.phoneTF.setText(""+rs.getLong("phone"));
        c.emailTF.setText(rs.getString("mail"));
        c.maritalTF.setText(rs.getString("marital_stat"));
        c.imageL.setIcon(new ImageIcon("C:\\Users\\user\\OneDrive\\Documents\\NetBeansProjects\\PoliceDBMS\\src\\resources\\Police\\"+rs.getString("id")+".jpg"));
        }
        rs.close();
        stmt.close();
        con.close();
        }
        catch(Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_infoBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JComboBox<String> critCB;
    private javax.swing.JTable dataTB;
    private javax.swing.JButton infoBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newEntryBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField searchTF;
    private javax.swing.JButton showAllBTN;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
